### ISSUE TITLE
关于模型的输出

### ISSUE THREAD

**Issue by hyxhyxhyxhyxhyx** [wangtao2001/acdc#1]
请问这个项目的输出没有经过图像分割后的图像文件吗？好像只有loss和dice

**Comment by wangtao2001** [comment]
您可以修改run.py下的train或者test函数，将模型的输出额外保存为图像文件 :)

**Comment by LebronMX-A** [comment]
请问您解决这个问题了吗，我该怎么修改run.PY

**Comment by wangtao2001** [comment]
> 请问您解决这个问题了吗，我该怎么修改run.PY

已新增了 predict.py
